url: http://deltacamino.github.io
baseurl: 

# Site settings
title: deltacamino
email: biuro@deltacamino.pl
description: "Cieczowe tłumiki drgań stalowych kominów przemysłowych - obniżenie kosztów inwestycji i eksploatacji przez redukcję drgań poprzecznych od wzbudzenia wirowego wywołanego oddziaływaniem wiatru. Weryfikacja skuteczności tłumienia z wykorzystaniem aparatury do pomiaru drgań."
collections:
  - realizations

collections:
  realizations:
    output: true

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: f0001c
  secondary: f0001c
  secondary-dark: 344144

# Team names, titles and social links
people:
- name: Marcin Wach
  pic: 1
  position: Prezes spółki
  resp: Realizacje
  email: marcin.wach@deltacamino.pl
- name: Jerzy Nowak
  pic: 2
  position: Wspólnik
  resp: Projektowanie i doradztwo techniczne
  email: jerzy.nowak@deltacamino.pl
- name: Damian Fijorek
  pic: 3
  position: Wspólnik
  resp: Projektowanie i weryfikacja
  email: damian.fijorek@deltacamino.pl

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
