url: http://damianfijorek.github.io
baseurl: /delta-camino-site

# Site settings
title: delta camino
email: damianfijorek@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
collections:
  - realizations

collections:
  realizations:
    output: true

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: f0001c
  secondary: f0001c
  secondary-dark: 344144

# Team names, titles and social links
people:
- name: Marcin Wach
  pic: 0
  position: Realizacje
- name: Jerzy Nowak
  pic: 0
  position: Projektowanie i doradztwo techniczne
- name: Damian Fijorek
  pic: 3
  position: Projektowanie i weryfikacja
  social:
    - title: linkedin
      url: https://pl.linkedin.com/in/damian-fijorek-02352161
  phone: 885 516 067

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
